user_pref("kmeleon.toolband.&Go Buttons.break", 0);
user_pref("kmeleon.toolband.&Go Buttons.index", 5);
user_pref("kmeleon.toolband.&Go Buttons.size", 63);
user_pref("kmeleon.toolband.&Go Buttons.visibility", true);
user_pref("kmeleon.toolband.&Main Bar.break", 1);
user_pref("kmeleon.toolband.&Main Bar.index", 3);
user_pref("kmeleon.toolband.&Main Bar.size", 206);
user_pref("kmeleon.toolband.&Main Bar.visibility", true);
user_pref("kmeleon.toolband.&Privacy Bar.break", 0);
user_pref("kmeleon.toolband.&Privacy Bar.index", 1);
user_pref("kmeleon.toolband.&Privacy Bar.size", 160);
user_pref("kmeleon.toolband.&Privacy Bar.visibility", true);
user_pref("kmeleon.toolband.Bookmarks.break", 1);
user_pref("kmeleon.toolband.Bookmarks.index", 8);
user_pref("kmeleon.toolband.Bookmarks.size", 1233);
user_pref("kmeleon.toolband.Bookmarks.visibility", true);
user_pref("kmeleon.toolband.Menu.break", 0);
user_pref("kmeleon.toolband.Menu.index", 0);
user_pref("kmeleon.toolband.Menu.size", 1064);
user_pref("kmeleon.toolband.Menu.visibility", true);
user_pref("kmeleon.toolband.Tab/&Window Buttons.break", 0);
user_pref("kmeleon.toolband.Tab/&Window Buttons.index", 7);
user_pref("kmeleon.toolband.Tab/&Window Buttons.size", 37);
user_pref("kmeleon.toolband.Tab/&Window Buttons.visibility", true);
user_pref("kmeleon.toolband.Tabs.break", 1);
user_pref("kmeleon.toolband.Tabs.index", 6);
user_pref("kmeleon.toolband.Tabs.size", 1233);
user_pref("kmeleon.toolband.Tabs.visibility", true);
user_pref("kmeleon.toolband.Throbber.break", 0);
user_pref("kmeleon.toolband.Throbber.index", 2);
user_pref("kmeleon.toolband.Throbber.size", 40);
user_pref("kmeleon.toolband.Throbber.visibility", true);
user_pref("kmeleon.toolband.URL Bar.break", 0);
user_pref("kmeleon.toolband.URL Bar.index", 4);
user_pref("kmeleon.toolband.URL Bar.size", 810);
user_pref("kmeleon.toolband.URL Bar.visibility", true);